### ISSUE TITLE
No Serial output when this function bearer_callback

### ISSUE THREAD

**Issue by syediddi** [MediaTek-Labs/aws_mbedtls_mqtt#1]
This seems to be weird. 

If the  function bearer_callback is present in the code, the serial simply doesn't output anything.

I tried nodejs sdk from amazon and the mqtt sample works perfect.

However even before trying the mqtt the function bearer_callback prevents anything to print on Serial monitory. If I remove the function and print on Serial Monitor it a at least prints.

Any idea whats going on?

Arduino 1.6.5-r5
Windows 10
MediaTek

**Comment by JasonMTK** [comment]
Hi, 

Did you replace the platform.txt file in your Arduino?

It seems like not only Mac need to replace the platform.txt. For windows 10, you may also need to do this step:

Noticed:  please replace platform.txt to the following place:

Arduino 1.5.7: /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/mtk/platform.txt

Arduino 1.6.5: /Users/{YOUR_USERNAME}/Library/Arduino15/packages/LinkIt/hardware/arm/1.1.17/platform.txt

You could download the platform.txt from this github.

Thanks,

**Comment by syediddi** [comment]
I see the platform.txt in this path.

C:\Users<username>\AppData\Roaming\Arduino15\packages\LinkIt\hardware\arm\1.1.17

Also, I was able to successfully execute the blink and wifi sample..The issue was with the mqtt sample and that particular function.

**Comment by JasonMTK** [comment]
Yes, you are correct. I upload a version for Windows platform.txt. Could you try to download it and replace it for the path C:\Users<username>\AppData\Roaming\Arduino15\packages\LinkIt\hardware\arm\1.1.17?

Let me know the issue would be fixed or not.

The reason for this problem is about compile options and may only happened to win10. We need to add "-ffunction-sections -fdata-sections" those two options in compiler.c.flags=-c and compiler.cpp.flags=-c in platform.txt.

**Comment by syediddi** [comment]
Man it worked. Thanks.
