### ISSUE TITLE
Shadow example question

### ISSUE THREAD

**Issue by ghost** [MediaTek-Labs/aws_mbedtls_mqtt#3]
I want to change the status of the on-board led(D13). So I add the below code,

`void windowActuate_Callback(const char *pJsonString, uint32_t JsonStringDataLen, jsonStruct_t *pContext) {

```
if (pContext != NULL) {
    Serial.print("\r\n\r\nDelta - Window state changed to ");
    Serial.println(*(bool *)(pContext->pData));
    Serial.println("\r\n\r\n");
    if((*(bool *)(pContext->pData)) == 1)
    {
        pinMode(13, OUTPUT);
        digitalWrite(13, HIGH);
    }
    else 
    {
        pinMode(13, OUTPUT);
        digitalWrite(13, LOW);
    }
}
```

}`

And in the aws iot web end, update the following:

```
{
  "desired": {
    "windowOpen": true
  },
  "reported": {
    "temperature": 22,
    "windowOpen": true
  }
}
```

It works well when the first time to update. But later it would not work any more. 

Do you guys know what happen?
Thanks.

**Comment by johnrotach** [comment]
Hi @loovee,

When you update the value in the AWS console are you changing the desired value?  The app is driven off of scenarios where there is a delta (desired state != reported state).

The general flow of this app would be:
- device comes online, reports window is closed ("reported":{"windowOpen":false})
- update desired state in console ("desired":{"windowOpen":true})
- this generates a "delta" (reported != desired) and service sends a delta to the device
- device sees desired state is open in delta message, changes state
- device updates reported state to be open ("reported":{"windowOpen":true})
- this resolves the delta because both desired and reported are true
- update desired state in console ("desired":{"windowOpen":false})
- this generates a "delta" (reported != desired) and service sends a delta to the device
- device sees desired state is closed in delta message, changes state
- device updates reported state to be closed ("reported":{"windowOpen":false})
- this resolves the delta because both desired and reported are false

And so on.  Hope this helps.

John
AWS IoT

**Comment by ghost** [comment]
Thanks John, I works now.
